# Generated by Django 6.0.4 on 2026-05-12 20:52

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('desired_position', models.CharField(max_length=150)),
                ('salary', models.IntegerField()),
                ('resume', models.FileField(upload_to='resume/')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
