# Generated by Django 6.0.4 on 2026-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='desired_position',
            field=models.CharField(max_length=150, verbose_name='Желаемая должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(max_length=200, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(upload_to='resume/', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.TextField(verbose_name='Навыки'),
        ),
    ]
