# Generated by Django 6.0.4 on 2026-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Введите название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Введите имя автора')),
                ('description', models.TextField(blank=True, verbose_name='Введите описание книги')),
                ('genre', models.CharField(blank=True, choices=[('Художественная литература', 'Художественная литература'), ('Нехудожественная литература', 'Нехудожественная литература'), ('Научная фантастика', 'Научная фантастика'), ('Фэнтези', 'Фэнтези'), ('Детектив', 'Детектив'), ('Биография', 'Биография'), ('История', 'История'), ('Роман', 'Роман'), ('Триллер', 'Триллер'), ('Другое', 'Другое')], default='Художественная литература', verbose_name='Введите жанр книги')),
                ('pages', models.PositiveIntegerField(default=20, null=True, verbose_name='Введите количество страниц')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Введите цену книги')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Введите дату публикации книги')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='Введите язык книги')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Введите издательство книги')),
                ('mark', models.FloatField(default=0.0, null=True, verbose_name='Введите рейтинг книги')),
            ],
        ),
    ]
