# Generated by Django 6.0.4 on 2026-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='Введите ISBN книги'),
        ),
    ]
