# Generated by Django 6.0.4 on 2026-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Загрузите обложку книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='install',
            field=models.FileField(blank=True, null=True, upload_to='book_files/', verbose_name='Загрузите файл книги'),
        ),
    ]
