# Generated by Django 6.0.4 on 2026-05-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_cover_remove_book_install_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Художественная литература', 'Художественная литература'), ('Нехудожественная литература', 'Нехудожественная литература'), ('Научная фантастика', 'Научная фантастика'), ('Фэнтези', 'Фэнтези'), ('Детектив', 'Детектив'), ('Биография', 'Биография'), ('История', 'История'), ('Роман', 'Роман'), ('Триллер', 'Триллер'), ('Другое', 'Другое')], default='Художественная литература', max_length=50, verbose_name='Введите жанр книги'),
        ),
    ]
