# Generated by Django 6.0.4 on 2026-05-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='choice_company',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.RemoveField(
            model_name='tourcompany',
            name='created_at',
        ),
    ]
