# Generated by Django 6.0.4 on 2026-05-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0002_rename_choice_company_review_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='horse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horse_tour.horse'),
        ),
    ]
