# Generated by Django 6.0.4 on 2026-05-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0003_review_horse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='horse_tour.tourcompany')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='horse_tour.horse')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='horse_tour.person')),
            ],
        ),
    ]
