# Generated by Django 6.0.4 on 2026-05-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='owner',
        ),
    ]
