# Generated by Django 6.0.4 on 2026-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0005_remove_horse_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
